package:
  name: eigen
  version: "3.2.5"
 
source:
  fn: eigen-eigen-bdd17ee3b1b3.tar.bz2
  url: http://bitbucket.org/eigen/eigen/get/3.2.5.tar.bz2
  md5: 21a928f6e0f1c7f24b6f63ff823593f5

build:
  number: 0

about:
  home: http://eigen.tuxfamily.org
  license: MPL2 
  license_file: COPYING.README
  summary: "Eigen - A C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms."
