# may want to at some point restrict Python version further
python:
  - 3.4
  - 3.5
  - 3.6 # [osx]
  # - 3.7 # no compatible pyqt4 packages

# numpy nodes use the c api, so we need to build variants
# and pin the build/run versions
# numpy:
#   - 1.11
  # - 1.12
  # - 1.13
  # - 1.14
  # - 1.15
  # - 1.16

