{% set version = "1.0.6" %}
package:
  name: gpi-core-nodes
  version: {{ version }}

source:
  git_rev: "v{{ version }}"
  git_url: https://github.com/gpilab/core-nodes.git

requirements:
  host:
    - gpi
    - eigen =3
    - fftw
    - numpy 1.11.* # forward-compatible ABI
    - python {{ python }}
  run:
    - eigen =3
    - {{ pin_compatible('fftw') }}
    - gpi
    - matplotlib >=2.1,<3 # [osx]
    - matplotlib <2 # [linux]
    # - numpy {{ numpy }}
    - {{ pin_compatible('numpy') }}
    # - python
    - {{ pin_compatible('python') }}
    - scipy

build:
  number: {{ os.environ["PKG_BUILDNUM"] }}
  # string: {{ os.environ["PKG_BUILD_STRING"] }}
  detect_binary_files_with_prefix: True

about:
  home: https://github.com/gpilab/core-nodes
  license: GPLv3
  summary: "Core nodes for the GPI development framework"
