package:
  name: gpi-core-nodes
  version: "0.6.0"

source:
  git_rev: py3k
  git_url: http://docbrown.local/kcii/core-nodes-github.git

requirements:
  build:
    - python >=3.4
    - gpi >=0.6.0
  run: # keep these strict for now
    - python >=3.4
    - gpi >=0.6.0

build:
  number: 0
  string: py3k
  detect_binary_files_with_prefix: True

about:
  home: https://github.com/gpilab/core-nodes
  license: GPLv3
  license_file: LICENSE
  summary: "Core nodes for the GPI development framework"

