package:
  name: gpi-core-nodes
  version: "1.0.4"

source:
  git_rev: v1.0.4
  git_url: https://github.com/gpilab/core-nodes.git

requirements:
  build:
    - gpi >=1.0
    - astyle 2.*
    - eigen
    - fftw
    - h5py
    - numba
    - numpy
    - pep8
    - pillow
    - psutil
    - pyflakes
    - pyopengl
    - python >=3.4
    - pyqt 4.*
    - qt 4.*
    - sip
    - scipy
    - qimage2ndarray
  run:
    - gpi >=1.0
    - astyle 2.*
    - eigen
    - fftw
    - h5py
    - matplotlib
    - numba
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - pep8
    - pillow
    - psutil
    - pyflakes
    - pyopengl
    - python >=3.4
    - pyqt 4.*
    - qt 4.*
    - sip
    - scipy
    - qimage2ndarray

build:
  number: {{ os.environ["PKG_BUILDNUM"] }}
  string: {{ os.environ["PKG_BUILD_STRING"] }}
  detect_binary_files_with_prefix: True

about:
  home: https://github.com/gpilab/core-nodes
  license: GPLv3
  summary: "Core nodes for the GPI development framework"
