{% set version = "1.0.6" %}
package:
  name: gpi-core-nodes
  version: {{ version }}

source:
  git_rev: "v{{ version }}"
  git_url: https://github.com/gpilab/core-nodes.git

requirements:
  build:
    - {{ compiler('cxx') }}
    - eigen
    - fftw
    - gpi
    - numpy {{ numpy }}
    - python {{ python }}
  run:
    - {{ pin_compatible('eigen') }}
    - {{ pin_compatible('fftw') }}
    - gpi
    - matplotlib >=2.1,<3
    - {{ pin_compatible('numpy') }}
    - python
    - pyqt {{ pyqt }}
    - qt {{ qt }}

build:
  number: {{ os.environ["PKG_BUILDNUM"] }}
  # string: {{ os.environ["PKG_BUILD_STRING"] }}
  detect_binary_files_with_prefix: True

about:
  home: https://github.com/gpilab/core-nodes
  license: GPLv3
  summary: "Core nodes for the GPI development framework"
