package:
  name: gpi-core-nodes
  version: "1.0.0" # [py3k]
  version: "0.6.0" # [py2k]

source:
  git_rev: py3k # [py3k]
  git_rev: develop # [py2k]
  git_url: https://github.com/gpilab/core-nodes.git
  #git_url: http://docbrown.local/kcii/core-nodes-github.git

requirements:
  build:
    - python >=3.4 # [py3k]
    - python >=2.6,<3 # [py2k]
    - gpi >=1.0 # [py3k]
    - gpi <1.0 # [py2k]
  run: # keep these strict for now
    - python >=3.4 # [py3k]
    - python >=2.6,<3 # [py2k]
    - gpi >=1.0 # [py3k]
    - gpi <1.0 # [py2k]

build:
  number: 0
  string: py{{ environ['CONDA_PY'] }}_{{ environ['PKG_BUILDNUM'] }}
  detect_binary_files_with_prefix: True

about:
  home: https://github.com/gpilab/core-nodes
  license: GPLv3
  summary: "Core nodes for the GPI development framework"
