package:
  name: gpi-core-nodes
  version: "1.0.3" # [py3k]
  version: "0.6.1" # [py2k]

source:
  git_rev: v1.0.3 # [py3k]
  git_rev: v0.6.0-rc # [py2k]
  git_url: https://github.com/gpilab/core-nodes.git

requirements:
  build:
    - python >=3.4 # [py3k]
    - python >=2.6,<3 # [py2k]
    - gpi >=1.0 # [py3k]
    - gpi <1.0 # [py2k]
  run: # keep these strict for now
    - python >=3.4 # [py3k]
    - python >=2.6,<3 # [py2k]
    - gpi >=1.0 # [py3k]
    - gpi <1.0 # [py2k]
    - pillow
    - numpy
    - scipy
    - matplotlib
    - pyopengl
    - h5py

build:
  number: {{ environ['PKG_BUILDNUM_STR'] }}
  string: {{ environ['FULL_BUILD_STR'] }}
  detect_binary_files_with_prefix: True

about:
  home: https://github.com/gpilab/core-nodes
  license: GPLv3
  summary: "Core nodes for the GPI development framework"
