package:
  name: fftw
  version: "3.3.4"
 
source:
  fn: fftw-3.3.4.tar.gz
  url: ftp://ftp.fftw.org/pub/fftw/fftw-3.3.4.tar.gz
  md5: 2edab8c06b24feeb3b82bbb3ebf3e7b3

build:
  number: 0
 
requirements:
  build:

about:
  home: http://www.fftw.org
  license: GPLv2
  license_file: COPYRIGHT
