package:
  name: astyle
  version: "2.05.1"

source:
  fn: astyle_2.05.1_macosx.tar.gz # [osx]
  url: http://downloads.sourceforge.net/project/astyle/astyle/astyle%202.05.1/astyle_2.05.1_macosx.tar.gz # [osx]
  md5: cb7cdfa645c155bb3ad20bc7d726f023 # [osx]
  fn: astyle_2.05.1_linux.tar.gz # [linux]
  url: http://downloads.sourceforge.net/project/astyle/astyle/astyle%202.05.1/astyle_2.05.1_linux.tar.gz # [linux]
  md5: 4142d178047d7040da3e0e2f1b030a1a # [linux]

  patches:
    - makefile_osx.patch # [osx]

build:
  number: 0
  detect_binary_files_with_prefix: True

about:
  home: http://astyle.sourceforge.net
  license: GPLv3
  license_file: doc/license.html
  summary: Artistic Style - A free, fast, and small automatic formatter for C, C++, C++/CLI, Objective‑C, C#, and Java source code
