package:
  name: gpi-docs
  version: "1.0.0"

source:
  git_rev: master
  git_url: https://github.com/gpilab/gpilab.github.io.git

requirements:
  build:
    - gpi >=0.6.0
    - python >=3.4 # [py3k]
    - python >=2.6,<3 # [py2k]
  run: # keep these strict for now
    - gpi >=0.6.0
    - python >=3.4 # [py3k]
    - python >=2.6,<3 # [py2k]

build:
  number: {{ environ['PKG_BUILDNUM'] }}
  string: py{{ environ['CONDA_PY'] }}_{{ environ['PKG_BUILDNUM'] }}{{ environ['RELEASE_STR'] }}
  detect_binary_files_with_prefix: True

about:
  home: http://docs.gpilab.com
  license: GPLv3
  license_file: LICENSE
  summary: "GPI Documentation"
