package:
  name: qimage2ndarray
  version: "1.5"

source:
  fn: qimage2ndarray-1.5.tar.gz
  url: https://pypi.python.org/packages/source/q/qimage2ndarray/qimage2ndarray-1.5.tar.gz
  md5: 733e68a04b2cc84ca9f680e37732262f

build:
  number: 0
  string: py{{ environ['CONDA_PY'] }}

requirements:
  build:
    - python >=3.4 # [py3k]
    - python >=2.6,<3 # [py2k]
    - setuptools
    - numpy

  run:
    - python >=3.4 # [py3k]
    - python >=2.6,<3 # [py2k]
    - numpy

test:
  # Python imports
  imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - nose
    - sip
    - qt
    - pyqt

about:
  home: https://github.com/hmeine/qimage2ndarray
  license: BSD License
  summary: 'Conversion between QImages and numpy.ndarrays.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
