package:
  name: gpi
  version: "1.0.0" # [py3k]
  version: "0.6.0" # [py2k]

source:
  git_rev: v1.0.0-rc # [py3k]
  git_rev: v0.6.0-rc # [py2k]
  git_url: https://github.com/gpilab/framework.git
  # git_url: git@docbrown.local:kcii/framework-github.git
  # git_url: http://docbrown.local/kcii/framework-github.git

requirements:
  run: # keep these strict for now
    - python >=3.4 # [py3k]
    - python >=2.6,<3 # [py2k]
    - numpy 1.9.*
    - scipy 0.16.*
    - matplotlib 1.4.*
    - qt <5
    - pyqt <5
    - pyopengl 3.*
    - psutil
    - h5py
    - sip
    - pyflakes
    - pep8
    - astyle >2.0,<3.0
    - eigen 3.2.5
    - fftw 3.3.4
    - qimage2ndarray >=1.4
  build:
    - python >=3.4 # [py3k]
    - python >=2.6,<3 # [py2k]

build:
  number: 0
  string: py{{ environ['CONDA_PY'] }}_{{ environ['PKG_BUILDNUM'] }}

about:
  home: http://gpilab.com
  license: GPLv3
  summary: "GPI - Graphical Programming Interface Development Framework"
