{% set version = "1.0.6" %}

package:
  name: gpi
  version: {{ version }}

source:
  git_rev: "v{{ version }}"
  git_url: https://github.com/gpilab/framework.git

requirements:
  build:
    - python {{ python }}
  run:
    - eigen
    - fftw
    - h5py
    - numpy >=1.11,<2
    - pillow
    - psutil
    - pyopengl
    - python
    - pyqt {{ pyqt }}
    # - qt {{ qt }}
    - sip
    - qimage2ndarray

build:
  number: {{ os.environ["PKG_BUILDNUM"] }}
  skip_compile_pyc:
    - "include/PyFI/*.py"

about:
  home: http://gpilab.com
  license: GPL3
  license_file: LICENSE
  summary: "GPI - Graphical Programming Interface Development Framework"
