package:
  name: gpi
  version: "0.6.0.n1"

source:
  git_rev: conda-package
  git_url: http://docbrown.local/kcii/framework-github.git
  patches:
    - gpi.patch
    - gpi_make.patch

requirements:
  run: # keep these strict for now
    - python >=2.6,<3
    - numpy 1.9.*
    - scipy 0.16.0
    - matplotlib 1.4.*
    - qt >4.8,<5
    - pyqt >4.8,<5
    - pyopengl 3.*
    - psutil
    - astyle >2,<3
    - eigen 3.2.5
    - fftw 3.3.4
    - h5py
    # pip qimage2ndarray

build:
  number: 1

about:
  home: http://gpilab.com
  license: GPLv3
  license_file: LICENSE
  summary: "GPI - Graphical Programming Interface Development Framework"
