package:
  name: gpi
  version: "1.0.3" # [py3k]

source:
  git_rev: v1.0.3 # [py3k]
  git_url: https://github.com/gpilab/framework.git

requirements:
  run: # keep these strict for now
    - python 3.5.* # [py3k]
    - nomkl
    - scipy
    - numpy
    - sip
    - pyflakes
    - pep8
    - psutil
    - h5py
    - pillow
    - numba
    - qt 4.8.*
    - pyqt 4.11.*
    - astyle >2.0,<3.0
    - eigen 3.2.5
    - fftw 3.3.4
    - qimage2ndarray >=1.4
  build:
    - python 3.5.* # [py3k]

build:
  number: {{ environ['PKG_BUILDNUM_STR'] }}
  string: {{ environ['FULL_BUILD_STR'] }}

about:
  home: http://gpilab.com
  license: GPLv3
  summary: "GPI - Graphical Programming Interface Development Framework"
